/**
 * Type definitions for component documentation
 * These types match the structure previously generated by Velite
 */

export type ComponentCategory = 'atoms' | 'molecules' | 'organisms' | 'dataviz';

export interface ComponentProp {
  name: string;
  type: string;
  default?: string;
  required?: boolean;
  description?: string;
}

/**
 * Definition for interactive props that can be modified in the playground
 */
export interface InteractiveProp {
  /** Name of the prop (must match a prop in props array) */
  name: string;
  /** Display label in the UI */
  label: string;
  /** Type of control to render */
  controlType: 'select' | 'boolean';
  /** Options for select control */
  options?: { value: string; label: string }[];
  /** Default value */
  defaultValue: string;
}

/**
 * Definition for design tokens used by a component
 */
export interface ComponentToken {
  /** Token name (e.g., "semantic-surface-interaction-strong") */
  name: string;
  /** Category of the token (e.g., "surface", "stroke", "text") */
  category: 'surface' | 'stroke' | 'text' | 'icon' | 'radius' | 'shadow' | 'spacing' | 'animation';
  /** Description of how the token is used */
  usage: string;
  /** CSS variable name */
  cssVariable: string;
}

export interface ComponentExample {
  title: string;
  description?: string;
  code: string;
  preview?: string;
}

export interface ComponentVariant {
  name: string;
  description?: string;
  code: string;
}

export interface ComponentSize {
  name: string;
  description?: string;
  code: string;
}

export interface ComponentState {
  name: string;
  description?: string;
  code: string;
}

export interface Component {
  title: string;
  description: string;
  category: ComponentCategory;
  component: string;
  importPath: string;
  props?: ComponentProp[];
  examples?: ComponentExample[];
  variants?: ComponentVariant[];
  sizes?: ComponentSize[];
  states?: ComponentState[];
  bestPractices?: string[];
  do?: string[];
  dont?: string[];
  accessibility?: string;
  /** Props that can be modified interactively in the playground */
  interactiveProps?: InteractiveProp[];
  /** Design tokens used by this component */
  tokens?: ComponentToken[];
}


