// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Component = Collections['components']['schema']['_output']
export declare const components: Component[]
